### ISSUE TITLE
Stata fails with java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/Extract2DDI#25]
its-meta:extract jon$ java -jar Extract2DDI.jar -f test-file-data-types.dta --format 3.2 --config format32-stata 
2022-11-15 08:42:48,454 [main] INFO  edu.cornell.ncrn.ced2ar.stata.StataReaderFactory - Stata Data file test-file-data-types.dta is not a Format 115.
2022-11-15 08:42:48,455 [main] INFO  edu.cornell.ncrn.ced2ar.stata.StataReaderFactory - Stata Data file test-file-data-types.dta is not a Format 114.
2022-11-15 08:42:48,455 [main] INFO  edu.cornell.ncrn.ced2ar.stata.StataReaderFactory - Stata Data file test-file-data-types.dta is not a Format 113.
2022-11-15 08:42:48,457 [main] INFO  edu.cornell.ncrn.ced2ar.stata.StataReaderFactory - Stata Data file test-file-data-types.dta is not a Format 117
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at edu.cornell.ncrn.ced2ar.stata.impl.DtaReader.readValueLabels(DtaReader.java:419)
	at edu.cornell.ncrn.ced2ar.stata.impl.Dta118Reader.readVariables(Dta118Reader.java:222)
	at edu.cornell.ncrn.ced2ar.stata.impl.Dta117Reader.<init>(Dta117Reader.java:65)
	at edu.cornell.ncrn.ced2ar.stata.impl.Dta118Reader.<init>(Dta118Reader.java:49)
	at edu.cornell.ncrn.ced2ar.stata.StataReaderFactory.getStataReader(StataReaderFactory.java:42)
	at edu.cornell.ncrn.ced2ar.ddigen.csv.StataCsvGenerator.generateVariablesCsv(StataCsvGenerator.java:40)
	at edu.cornell.ncrn.ced2ar.ddigen.DdiLifecycleGenerator.generateVariablesCsv(DdiLifecycleGenerator.java:55)
	at edu.cornell.ncrn.ced2ar.ddigen.GenerateDDI32.generateDDI(GenerateDDI32.java:34)
	at edu.cornell.ncrn.ced2ar.ddigen.Main.main(Main.java:132)

**Comment by alkondrashov** [comment]
@spuddybike , could you provide your config file named format32-stata please?

**Comment by alkondrashov** [comment]
Just have sent you the recent jar file over the email to try replicating the OutOfMemory error

**Comment by alkondrashov** [comment]
Have replicated it with the recent dta file. Here is why the exception is hapenning:

<img width="807" alt="Screenshot 2024-03-14 at 22 28 36" src="https://github.com/CLOSER-Cohorts/Extract2DDI/assets/4246666/f922044a-028f-4edc-a399-0749a2d1970b">

In essence, the numberOfEntries variable gets to `1818389564` and when we initialise array of ints with that size we get OutOfMemory error. 

The exception is hapenning in `edu.cornell.ncrn.ced2ar.stata.impl.DtaReader`

**Comment by alkondrashov** [comment]
Based on stepping through the code, @spuddybike and I uncovered that `OutOfMemory` resulted from an incorrect value being read into numberOfEntries variable from a file.

**Comment by spuddybike** [comment]
@alkondrashov see https://www.loc.gov/preservation/digital/formats/fdd/fdd000471.shtml This I think might help in resolving the OOM error, as it indicates where the Number ofEntries is stored.

**Comment by spuddybike** [comment]
@alkondrashov see also https://www.stata.com/help.cgi?dta section 5

**Comment by alkondrashov** [comment]
As discussed, @spuddybike will provide another sample .dta file to test this error. We discovered that the issue is because the variables are being read incorrectly.

**Comment by spuddybike** [comment]
[test-file-data-types-118.dta.zip](https://github.com/CLOSER-Cohorts/Extract2DDI/files/14811498/test-file-data-types-118.dta.zip)
@alkondrashov file saved to Format 118 musing Stata for testing

**Comment by spuddybike** [comment]
Error created by SPSS export to Stata

**Comment by spuddybike** [comment]
SPSS Error
